USE test;

DROP TABLE Product;

CREATE TABLE IF NOT EXISTS Product (
  product_id INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  NAME VARCHAR(255) NOT NULL COMMENT '产品名称',
  CODE VARCHAR(255) NOT NULL COMMENT '产品编码',
  price DOUBLE NOT NULL DEFAULT 0.0,
  amount INT NOT NULL DEFAULT 0,
  PRIMARY KEY (product_id)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

ALTER TABLE Product ADD UNIQUE INDEX(NAME,CODE);

SHOW INDEX FROM test.Product;

SELECT * FROM test.`Product`;


